backend:
  name: git-gateway
local_backend: true
media_folder: static/img
public_folder: /img
collections:
  - name: portfolio
    label: Portfolio
    label_singular: Portfolio
    folder: src/portfolio
    create: true
    preview_path: 'portfolio/{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          label: 'Date',
          name: 'date',
          widget: 'datetime',
          format: 'MMMM D, YYYY',
          dateFormat: 'MMMM D, YYYY',
          timeFormat: false
        }
      - { label: "Featured Image", name: "featured_image", widget: image}
      - { label: "Width", name: 'width', widget: select, options: [{ label: "Small", value: "600" },{ label: "Medium", value: "750" },{label: "Large", value: "900" }]}
  - name: blog
    label: Blog Posts
    label_singular: Blog Post
    folder: src/blog-posts
    create: true
    preview_path: 'blog/{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - {
          label: 'Date',
          name: 'date',
          widget: 'datetime',
          format: 'MMMM D, YYYY',
          dateFormat: 'MMMM D, YYYY',
          timeFormat: false
        }
      - { label: 'Author', name: 'author', widget: 'string' }
      - { label: "Featured Image", name: "featured_image", widget: image}
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: "navbarAndFooter"
    label: "Navbar & Footer"
    files:
      - file: "src/pages/navbar/index.md"
        label: "Navbar"
        name: "navbar"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "navbar" }
          - {
              label: "Menu Items",
              name: "menuItems",
              widget: "list",
              fields:
                [
                  { label: "Label", name: "label", widget: "string" },
                  { label: "Link Type", name: "linkType", widget: "select", options: ["internal", "external"] },
                  { label: "Link URL", name: "linkURL", widget: "string", hint: "Use a relative URL (e.g. /about) if the link is an internal link." },
                ],
            }
      - file: "src/pages/footer/index.md"
        label: "Footer"
        name: "footer"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "footer" }
          - {
              label: "Logo Image & Tagline",
              name: "logoImage",
              widget: "object",
              fields:
                [
                  { label: "Image", name: "image", widget: "image" },
                  { label: "Image Description", name: "imageAlt", widget: "string" },
                  { label: "Tagline", name: "tagline", widget: "string" },
                ],
            }
          - {
              label: "Social Links",
              name: "socialLinks",
              widget: "list",
              fields:
                [
                  { label: "Image", name: "image", widget: "image" },
                  { label: "Image Description", name: "imageAlt", widget: "string" },
                  { label: "Label", name: "label", widget: "string" },
                  { label: "Link URL", name: "linkURL", widget: "string" },
                ],
            }